// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(POSDbContext))]
    [Migration("20251013220056_AddPermissionSystem")]
    partial class AddPermissionSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExteriorNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteriorNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Customer Relationship Management",
                            IsActive = true,
                            Name = "CRM"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sales Management",
                            IsActive = true,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Product Management",
                            IsActive = true,
                            Name = "Products"
                        },
                        new
                        {
                            Id = 4,
                            Description = "User Management",
                            IsActive = true,
                            Name = "Users"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Crear clientes",
                            ModuleId = 1,
                            Name = "Create",
                            Resource = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ver clientes",
                            ModuleId = 1,
                            Name = "Read",
                            Resource = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Actualizar clientes",
                            ModuleId = 1,
                            Name = "Update",
                            Resource = "Customer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Eliminar clientes",
                            ModuleId = 1,
                            Name = "Delete",
                            Resource = "Customer"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Crear ventas",
                            ModuleId = 2,
                            Name = "Create",
                            Resource = "Sale"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ver ventas",
                            ModuleId = 2,
                            Name = "Read",
                            Resource = "Sale"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Actualizar ventas",
                            ModuleId = 2,
                            Name = "Update",
                            Resource = "Sale"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Eliminar ventas",
                            ModuleId = 2,
                            Name = "Delete",
                            Resource = "Sale"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Crear productos",
                            ModuleId = 3,
                            Name = "Create",
                            Resource = "Product"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ver productos",
                            ModuleId = 3,
                            Name = "Read",
                            Resource = "Product"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Actualizar productos",
                            ModuleId = 3,
                            Name = "Update",
                            Resource = "Product"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Eliminar productos",
                            ModuleId = 3,
                            Name = "Delete",
                            Resource = "Product"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Crear usuarios",
                            ModuleId = 4,
                            Name = "Create",
                            Resource = "User"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Ver usuarios",
                            ModuleId = 4,
                            Name = "Read",
                            Resource = "User"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Actualizar usuarios",
                            ModuleId = 4,
                            Name = "Update",
                            Resource = "User"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Eliminar usuarios",
                            ModuleId = 4,
                            Name = "Delete",
                            Resource = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Acceso completo al sistema",
                            IsActive = true,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Acceso básico al sistema",
                            IsActive = true,
                            Name = "Usuario"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Acceso a ventas y clientes",
                            IsActive = true,
                            Name = "Vendedor"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Acceso a productos",
                            IsActive = true,
                            Name = "Almacenista"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5732),
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5734),
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5735),
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5735),
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5735),
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5736),
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5736),
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5737),
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5737),
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5737),
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5738),
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5738),
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5738),
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5738),
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5738),
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5739),
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5755),
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5756),
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5757),
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5764),
                            PermissionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5764),
                            PermissionId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5765),
                            PermissionId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5765),
                            PermissionId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5766),
                            PermissionId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5766),
                            PermissionId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5767),
                            PermissionId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5775),
                            PermissionId = 9,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5775),
                            PermissionId = 10,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5776),
                            PermissionId = 11,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(5776),
                            PermissionId = 12,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sales", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Company_ID")
                        .HasColumnType("int");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Impuestos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimoCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warehouse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Code = "ADMIN001",
                            CreatedAt = new DateTime(2025, 10, 13, 22, 0, 56, 643, DateTimeKind.Utc).AddTicks(6292),
                            Email = "admin@sistema.com",
                            Name = "Administrador",
                            PasswordHash = new byte[] { 36, 11, 229, 24, 250, 189, 39, 36, 221, 182, 240, 78, 235, 29, 165, 150, 116, 72, 215, 232, 49, 192, 140, 143, 168, 34, 128, 159, 116, 199, 32, 169 },
                            Phone = "1234567890",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.HasOne("Domain.Entities.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
